title: Bits and Bolts Blog
theme: cayman
author: Alex
email: your-email@example.com
description: >-
  A badass blog about wrenching, coding, and microelectronics projects.
theme: minima
baseurl: "/bits_and_bolts" # the subpath of your site, e.g. /blog
url: "https://alexanderenrique.github.io" # your GitHub Pages URL

# Build settings
markdown: kramdown
collections:
  wrenching:
    output: true
  coding:
    output: true
  microelectronics:
    output: true 