title: Bits and Bolts Blog
theme: minima
author: Alex
email: your-email@example.com
description: >-
  A badass blog about wrenching, coding, and microelectronics projects.
baseurl: "/bits_and_bolts" # the subpath of your site, e.g. /blog
url: "https://alexanderenrique.github.io" # your GitHub Pages URL

# Build settings
markdown: kramdown
collections:
  wrenching:
    output: true
  coding:
    output: true
  microelectronics:
    output: true

# Disable automatic navigation
show_excerpts: false
show_downloads: false 