site_name: Bits and Bolts Blog
site_description: A badass blog about wrenching, coding, and microelectronics projects
site_author: Alex
site_url: https://alexanderenrique.github.io/bits_and_bolts/

# Repository
repo_name: alexanderenrique/bits_and_bolts
repo_url: https://github.com/alexanderenrique/bits_and_bolts
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  font:
    text: merriweather
    code: merriweather
    heading: merriweather
    monospace: merriweather
    weights: [400, 700, 900]
    styles: [normal, italic]

  icon:
    logo: fontawesome/solid/wrench
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  palette:
    ## Dark mode
    - scheme: slate
      primary: green
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    ## Light mode
    - scheme: standard
      primary: green
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.integrate


# Custom CSS to hide TOC
extra_css:
  - stylesheets/extra.css
  - stylesheets/3d-models.css

# Navigation
nav:
  - Home: index.md
  - Coding Projects:
    - Overview: coding/index.md
    - NEMO Projects:
      - NEMO Merger: coding/nemo-merger.md
      - NEMO to Drive: coding/nemo-to-drive.md
    - ChatBot Tools:
      - Meeting Notes Bot: coding/chatbot/meeting_notes.md
      - Work Log Bot: coding/chatbot/WorkLog.md
  - Wrenching Projects:
    - Overview: wrenching/index.md
    - 1968 Thunderbird: wrenching/thunderbird-restoration.md
    - 3D Models: wrenching/3d-models.md
  - Microelectronics:
    - Overview: microelectronics/index.md
    - Smart Thunderbird: microelectronics/Smart-T-Bird.md
  - General:
    - Overview: general/index.md
    - Today I Learned: general/Today-I-Learned.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alexanderenrique
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

# Copyright
copyright: Copyright &copy; 2024 Alex
