site_name: Bits and Bolts Blog
site_description: A badass blog about wrenching, coding, and microelectronics projects
site_author: Alex
site_url: https://alexanderenrique.github.io/bits_and_bolts/

# Repository
repo_name: alexanderenrique/bits_and_bolts
repo_url: https://github.com/alexanderenrique/bits_and_bolts
edit_uri: edit/main/docs/

# Theme
theme:
  name: cinder


# Custom CSS to hide TOC
extra_css:
  - stylesheets/extra.css
  - stylesheets/3d-models.css

# Navigation
nav:
  - Home: index.md
  - Coding Projects:
    - Overview: coding/index.md
    - NEMO Projects:
      - NEMO Merger: coding/nemo-merger.md
      - NEMO to Drive: coding/nemo-to-drive.md
    - ChatBot Tools:
      - Meeting Notes Bot: coding/chatbot/meeting_notes.md
      - Work Log Bot: coding/chatbot/WorkLog.md
  - Wrenching Projects:
    - Overview: wrenching/index.md
    - 1968 Thunderbird: wrenching/thunderbird-restoration.md
    - 3D Models: wrenching/3d-models.md
  - Microelectronics:
    - Overview: microelectronics/index.md
    - Smart Thunderbird: microelectronics/Smart-T-Bird.md
  - General:
    - Overview: general/index.md
    - Today I Learned: general/Today-I-Learned.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alexanderenrique
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

# Copyright
copyright: Copyright &copy; 2024 Alex
